---
title: 飞哥博客(MY RULE) 
baseurl: ""
techurl: "/tech.html"
enteurl: "/ente.html"

desc: 一个有说有笑又有料的私人博客.
#about: I am a web developer, software engineer, and project manager currently living in Collinsville, Illinois. I'm a little weird but pretty friendly.
about: 小时候曾认为自己是一只贪玩的小虎，贪玩儿不知归路；玩着玩着就长大了，认为自己是个看客，看人生百态,品世态炎凉；又后来呀，我把自己伪装成一块冰，理性的看待每一件事，听世间的蜚言蜚语；现在吧，我相信学无先后，达者为师，我为前车之师,后车引以为鉴。
#image: https://pinto-light.glitch.me/?width=500&height=500&url=https://i.imgur.com/mxUVc2x.jpg&extension=jpg
image:./images/avatar.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
